language: node_js
sudo: false
node_js:
- '7'

branches:
  only:
  - master

deploy:
  provider: heroku
  api_key:
    secure: $key
  app: gametes
  on:
    repo: pryahin/game_frontend
    branch: master
  skip_cleanup: true

script:
  - npm i
