language: node_js
sudo: false
node_js:
- '7'

branches:
  only:
  - master

deploy:
  provider: heroku
  api_key:
    secure: $key228
  app: front228
  on:
    repo: ilyamoskalev/CG
    branch: master
  skip_cleanup: true

script:
  - npm i
